name: pokemon-legendary-estimator
channels:
  - defaults
dependencies:
  - python=3.8
  - pip
  - pip:
    - scikit-learn==1.1.2
    - mlflow>=1.28.0
    - pandas>=1.2.2
    - numpy>=1.20.1
    - shap>=0.39.0
    - matplotlib>=3.4.1
    - boto3==1.17.19